securityonion-web-page: only restart apache if it was already running Security-Onion-Solutions/security-onion#1520

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -73,8 +73,10 @@ case "$1" in
 	# Enable securityonion site
 	a2ensite securityonion || echo "Error enabling securityonion site in Apache."
 
-	# Restart Apache
-	apache2ctl restart || echo "Error restarting Apache."
+	# If Apache is currently running, restart it
+	if /usr/bin/pgrep apache2 >/dev/null ; then
+		/usr/sbin/apache2ctl restart || echo "Error restarting Apache."
+	fi
 
     ;;
 
