migrate ELSA local.php to new location

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -30,8 +30,14 @@ case "$1" in
 		fi
 	fi
 
-	# Add ELSA local queries if not already present
+	# Check for local queries and migrate if necessary
+	OLDFILE="/var/www/elsa/local.php"
 	FILE="/var/www/so/elsa/local.php"
+	if [ -f $OLDFILE ]; then
+		cp $OLDFILE $FILE || echo "Error copying $OLDFILE to $FILE."
+	fi
+
+	# Add ELSA local queries if not already present
 	if [ -f $FILE ]; then
 		echo "* $FILE already exists, not overwriting."
 	else
